title: My GitHub Page
description: A simple site built with Jekyll and GitHub Pages
author: Ankpens
email: makankshya21@example.com

# Theme (change to any other supported theme if desired)
theme: jekyll-theme-modernist

# Base settings
markdown: kramdown
permalink: pretty

# GitHub Pages automatically uses safe mode and disables some plugins
# These plugins are safe and commonly used:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these from the build (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

    # remote_theme: mmistakes/minimal-mistakes
    # gem "jekyll-remote-theme"

